=== D31nS3b1/testcenter/definitions/vo_Booklet.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="vo_Booklet" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="Booklet">
    <xs:complexType>
      <xs:all>

        <xs:element name="Metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Id" type="xs:ID" />
              <xs:element name="Label" type="xs:string" />
              <xs:element name="Description" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="BookletConfig" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Config" type="ConfigType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Units" type="FirstTestletType" />
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TestletRestrictionsType">
    <xs:sequence>
      <xs:element name="CodeToEnter" type="CodeToEnterRestrictionType" minOccurs="0" />
      <xs:element name="TimeMax" type="TimeMaxRestrictionType" minOccurs="0" />
      <xs:element name="DenyNavigationOnIncomplete" type="DenyNavigationOnIncompleteRestrictionType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TimeMaxRestrictionType">
    <xs:attribute name="minutes" type="xs:positiveInteger"/>
  </xs:complexType>

  <xs:complexType name="CodeToEnterRestrictionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="code" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="DenyNavigationOnIncompleteRestrictionValue">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ON"/>
      <xs:enumeration value="OFF"/>
      <xs:enumeration value="ALWAYS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="DenyNavigationOnIncompleteRestrictionType">
    <xs:simpleContent><!-- TODO should be camleCase.. -->
      <xs:extension base="xs:string">
        <xs:attribute type="DenyNavigationOnIncompleteRestrictionValue" name="presentation" />
        <xs:attribute type="DenyNavigationOnIncompleteRestrictionValue" name="response" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="FirstRestrictionsType">
    <xs:all>
      <xs:element name="TimeMax" type="TimeMaxRestrictionType" minOccurs="0" />
      <xs:element name="DenyNavigationOnIncomplete" type="DenyNavigationOnIncompleteRestrictionType" minOccurs="0" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="TestletType">
    <xs:sequence>
      <xs:element name="Restrictions" type="TestletRestrictionsType" minOccurs="0" />
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Unit" type="UnitType" />
          <xs:element name="Testlet" type="TestletType" />
        </xs:choice>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="label" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="FirstTestletType">
    <xs:sequence>
      <xs:element name="Restrictions" type="FirstRestrictionsType" minOccurs="0" />
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Unit" type="UnitType" />
          <xs:element name="Testlet" type="TestletType" />
        </xs:choice>
      </xs:sequence>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="UnitType">
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="label" type="xs:string" use="required"/>
    <xs:attribute name="labelshort" type="xs:string"/>
    <xs:attribute name="alias" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="ConfigType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="key" type="xs:ID" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== D31nS3b1/testcenter/sampledata/Booklet.xml
<Booklet
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../definitions/vo_Booklet.xsd"
>
  <Metadata>
    <Id>BOOKLET.SAMPLE</Id>
    <Label>Sample booklet</Label>
    <Description>This a a sample booklet for testing/development/showcase purposes.</Description>
    <Owner>__USER_NAME__</Owner>
    <Lastchange>2019-10-27T13:37:00</Lastchange>
    <Status>unknown</Status>
    <Project>sample</Project>
  </Metadata>

  <BookletConfig>
    <Config key="NextOnlyIfPresentationComplete"/>
    <Config key="NavPolicy"/>
    <Config key="NavButtons">on</Config>
    <Config key="PageNavBar">on</Config>
    <Config key="Logging">on</Config>
    <Config key="Loading">on</Config>
  </BookletConfig>

  <Units id="section_A" label="section_A">
    <Restrictions>
      <TimeMax parameter="string">60</TimeMax>
    </Restrictions>

    <Testlet>

      <Unit id="UNIT.SAMPLE" label="the great sample unit" labelshort="sample unit" />
    </Testlet>

    <Testlet>

      <Restrictions>
        <CodeToEnter parameter="sample">Please insert the word `sample`.</CodeToEnter>
        <TimeMax parameter="1" />
      </Restrictions>

      <Unit id="UNIT.SAMPLE-2" label="the great sample unit" labelshort="sample unit" />
    </Testlet>

  </Units>
</Booklet>

=== D31nS3b1/testcenter/sampledata/system-test/CY_BKL_TestletRestrictionParam_3.xml
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/16.0.0/definitions/vo_Booklet.xsd">
	<Metadata>
		<Id>CY-BkltTsltRestr-3</Id>
		<Label>Test Bklt Configs value-3</Label>
		<Description>Testen der dritte Werte</Description>
	</Metadata>

	<BookletConfig>

		<!--its only important to navigated to the next page if page navibuttons are disabled -->
		<Config key="pagingMode">buttons</Config>

  </BookletConfig>

	<Units>

		<Testlet id="Tslt1" label="Aufgabenblock">
			<Restrictions>
        <TimeMax minutes="2" leave = "forbidden"/>
        <DenyNavigationOnIncomplete presentation="OFF" response="OFF" />
			</Restrictions>
			<Unit id="CY-Unit.Sample-101" label="Aufgabe1" labelshort="1"/>
			<Unit id="CY-Unit.Sample-102" label="Aufgabe2" labelshort="2"/>
		</Testlet>
		
		<Unit id="CY-Unit.Sample-104" label="Endseite" labelshort="3"/>
	</Units>
</Booklet>
